{
    "events": [
        {
            "timestamp": "2021-08-22T13:11:55.017000-06:00",
            "type": "ExecutionStarted",
            "id": 1,
            "previousEventId": 0,
            "executionStartedEventDetails": {
                "input": "{}",
                "inputDetails": {
                    "truncated": false
                },
                "roleArn": "arn:aws:iam::CENSORED:role/IntegErrorMessage-IntrinsicValidatorStateMachineRo-WNIYREYDSF71"
            }
        },
        {
            "timestamp": "2021-08-22T13:11:55.062000-06:00",
            "type": "ParallelStateEntered",
            "id": 2,
            "previousEventId": 0,
            "stateEnteredEventDetails": {
                "name": "Validations",
                "input": "{}",
                "inputDetails": {
                    "truncated": false
                }
            }
        },
        {
            "timestamp": "2021-08-22T13:11:55.062000-06:00",
            "type": "ParallelStateStarted",
            "id": 3,
            "previousEventId": 2
        },
        {
            "timestamp": "2021-08-22T13:11:55.062000-06:00",
            "type": "TaskStateEntered",
            "id": 4,
            "previousEventId": 3,
            "stateEnteredEventDetails": {
                "name": "[0] Check That Error Messages Show",
                "input": "{}",
                "inputDetails": {
                    "truncated": false
                }
            }
        },
        {
            "timestamp": "2021-08-22T13:11:55.062000-06:00",
            "type": "TaskScheduled",
            "id": 5,
            "previousEventId": 4,
            "taskScheduledEventDetails": {
                "resourceType": "lambda",
                "resource": "invoke",
                "region": "ca-central-1",
                "parameters": "{\"FunctionName\":\"arn:aws:lambda:ca-central-1:CENSORED:function:IntegErrorMessage-AlwaysFails0D393A9D-iNl73HRnjvmP\",\"Payload\":{}}"
            }
        },
        {
            "timestamp": "2021-08-22T13:11:55.131000-06:00",
            "type": "TaskStarted",
            "id": 6,
            "previousEventId": 5,
            "taskStartedEventDetails": {
                "resourceType": "lambda",
                "resource": "invoke"
            }
        },
        {
            "timestamp": "2021-08-22T13:11:55.390000-06:00",
            "type": "TaskFailed",
            "id": 7,
            "previousEventId": 6,
            "taskFailedEventDetails": {
                "resourceType": "lambda",
                "resource": "invoke",
                "error": "Exception",
                "cause": "{\"errorMessage\":\"An expected failure\",\"errorType\":\"Exception\",\"stackTrace\":[\"  File \\\"/var/task/index.py\\\", line 3, in handler\\n    raise Exception('An expected failure')\\n\"]}"
            }
        },
        {
            "timestamp": "2021-08-22T13:11:55.422000-06:00",
            "type": "TaskStateAborted",
            "id": 8,
            "previousEventId": 7
        },
        {
            "timestamp": "2021-08-22T13:11:55.422000-06:00",
            "type": "ParallelStateFailed",
            "id": 9,
            "previousEventId": 7
        },
        {
            "timestamp": "2021-08-22T13:11:55.455000-06:00",
            "type": "ExecutionFailed",
            "id": 10,
            "previousEventId": 9,
            "executionFailedEventDetails": {
                "error": "Exception",
                "cause": "{\"errorMessage\":\"An expected failure\",\"errorType\":\"Exception\",\"stackTrace\":[\"  File \\\"/var/task/index.py\\\", line 3, in handler\\n    raise Exception('An expected failure')\\n\"]}"
            }
        }
    ]
}
